default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
        require_serial: true
      - id: end-of-file-fixer
        require_serial: true
      # - id: check-docstring-first
      - id: check-yaml
        require_serial: true
      - id: debug-statements
        require_serial: true
      - id: detect-private-key
        require_serial: true
      - id: check-executables-have-shebangs
        require_serial: true
      - id: check-toml
        require_serial: true
      - id: check-case-conflict
        require_serial: true
      - id: check-added-large-files
        require_serial: true

  # python code formatting
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: [--line-length, "99"]
        require_serial: true


  # python import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        require_serial: true


  # python upgrading syntax to newer version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
        require_serial: true


  # python docstring formatting
  - repo: https://github.com/myint/docformatter
    rev: v1.5.1
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries=99, --wrap-descriptions=99]
        require_serial: true


  # python check (PEP8), programming errors and code complexity
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--ignore", "E501,F401,F841,W504,W503,E203", "--exclude", "logs/*,data/*"]
        require_serial: true

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args: ["--in-place", "--expand-star-imports", "--remove-all-unused-imports", "--ignore-init-module-imports"]
        require_serial: true


  # NOTE: Disabling this, it's annoying.
  # python security linter
  # - repo: https://github.com/PyCQA/bandit
  #   rev: "1.7.1"
  #   hooks:
  #     - id: bandit
  #       args: ["-s", "B101"]

  # NOTE: Disabling this, since I'm having the glib-c2.29 weird bug.
  # # yaml formatting
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v2.7.1
  #   hooks:
  #     - id: prettier
  #       types: [yaml]

  # jupyter notebook cell output clearing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        require_serial: true


  # md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter
          # - mdformat-toc
          # - mdformat-black
        require_serial: true


  # word spelling linter
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        args:
          - --skip=logs/**,data/**
          # - --ignore-words-list=abc,def
        require_serial: true
